### PR TITLE
Fix process exit issue

### PR DESCRIPTION
**Pull request by fatedier**
Implements enhanced stability and error handling in GoSSH and NativeSSH runners

- **Context Management**: Introduces context management in both `gssh_runner.go` and `nssh_runner.go` to gracefully handle goroutine lifecycles. This ensures that all running processes can be properly terminated, preventing unexpected exits.
- **Error Handling**: Adds error handling mechanisms to catch and log errors during the tunnel client creation and command execution phases. This helps in identifying issues without causing the process to exit unexpectedly.
- **Graceful Shutdown**: Implements a `cancelFunc` in both runners to ensure that all goroutines are signaled to stop during the shutdown phase. This contributes to a more stable and controlled shutdown process.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gofrp/tiny-frpc/issues/9?shareId=34b0293f-4373-4ff3-9d98-f17f8b5f51c2).

### CODE REVIEW

**Comment by fatedier** [comment]
Introduce context cancellation in SSH runners for improved goroutine management and cleanup.

- Add `context.Context` and `context.CancelFunc` to both `GoSSHRun` and `NativeSSHRun` structs to manage the lifecycle of goroutines more effectively.
- Implement context cancellation in the `Close` method of both runners to ensure all running goroutines are signaled to stop, facilitating a cleaner shutdown process.
- Modify the `Run` method in `NativeSSHRun` to utilize the inherited context for each command execution, allowing for better control and cancellation of individual SSH command executions.


---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gofrp/tiny-frpc/pull/11?shareId=8a5c7ac9-8caf-4021-b200-0dfae725a9dd).

**Comment by fatedier** [comment]
Refactor context management in NativeSSHRun's Run method to use a shared context.

- Remove the creation of a new context within each goroutine in the `Run` method, simplifying context management.
- Utilize the `nr.ctx` directly in goroutines for executing SSH commands, ensuring all goroutines share the same parent context for better control and cleanup.


---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gofrp/tiny-frpc/pull/11?shareId=0abc601b-e619-4813-bf0d-8d07626a3eeb).

**Comment by fatedier** [comment]
Removes the unused `time` package import from `nssh_runner.go` to clean up the code.

- Introduces a context with cancellation to manage goroutine lifecycles more effectively.
- Ensures all goroutines are signaled to stop by calling the cancel function in the `Close` method.


---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gofrp/tiny-frpc/pull/11?shareId=7cf20ef8-16de-41a7-b5b1-7bca16e8faa0).

**Comment by fatedier** [comment]
Refactor the NativeSSHRun struct and its methods to use a shared context for command execution.

- Introduce a shared context and cancel function in the `NativeSSHRun` struct to manage the lifecycle of goroutines and command execution.
- Modify the `NewCmdWrapper` and `ExecuteCommand` calls to use the shared context instead of creating a new one each time, ensuring consistent cancellation behavior across all command executions.
- Add a call to the cancel function in the `Close` method to ensure all running goroutines are properly signaled to stop.


---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/gofrp/tiny-frpc/pull/11?shareId=cfea7129-5ad6-4209-bc4c-427edfc366e2).

**Review by blizard863 — APPROVED** [review]

**Pull request merged**
